#!/usr/bin/perl

# Copyright (C) 2008-2009, Sebastian Riedel.

use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../lib";


# Check if Mojo is installed
eval 'use Mojolicious::Commands';
if ($@) {
    print <<EOF;
It looks like you don't have the Mojo Framework installed.
Please visit http://mojolicious.org for detailed installation instructions.

EOF
    exit;
}


$ENV{MOJO_APP} = 'DictyREST';

# Start commands
Mojolicious::Commands->start;

